// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftupfqyteovyscvvnidp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0dXBmcXl0ZW92eXNjdnZuaWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NzExMTQsImV4cCI6MjA3MzA0NzExNH0.JSkzrsqN37M3PSs8Xc-tYjZIColuGiUkxFTGR1djleE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});